project:
  type: sdca-theme

website:
  title: "CGM-AP"
  site-url: "https://steno-aarhus.github.io/cgm-ap/"
  repo-url: "https://github.com/steno-aarhus/cgm-ap"
  navbar:
    pinned: true
    left:
      - href: about.qmd

format: 
  sdca-theme-html:
    theme:
      - brand
      - theme.scss

editor:
  markdown:
    wrap: 72
    canonical: true
